# Generated by Django 2.2.4 on 2019-08-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('is_bot', models.BooleanField(default=False)),
                ('session', models.CharField(blank=True, choices=[('DAY', 'Day'), ('EVE', 'Evening')], max_length=3)),
                ('access_count', models.IntegerField(default=0)),
                ('is_manually_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.Track')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
    ]
