# Generated by Django 2.2.4 on 2019-09-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ('-updated_at',)},
        ),
    ]
