# Generated by Django 2.2.4 on 2019-08-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3)),
                ('value', models.IntegerField()),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('DAY', 'Day'), ('EVE', 'Evening')], max_length=3)),
                ('start_date', models.DateField(help_text='Date is inclusive.', verbose_name='rule start date')),
                ('end_date', models.DateField(help_text='Date is inclusive.', verbose_name='rule end date')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='schedules.Course')),
                ('days', models.ManyToManyField(related_name='rules', to='schedules.Day')),
                ('tracks', models.ManyToManyField(related_name='rules', to='schedules.Track')),
            ],
            options={
                'default_related_name': 'rules',
            },
        ),
    ]
