# Generated by Django 2.2.4 on 2019-08-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'default_related_name': 'schedules', 'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.Course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tracks',
            field=models.ManyToManyField(related_name='schedules', to='schedules.Track'),
        ),
    ]
