# Generated by Django 2.2.4 on 2019-08-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20190830_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerule',
            options={'default_related_name': 'rules', 'verbose_name': 'Schedule Generating Rule', 'verbose_name_plural': 'Schedule Generating Rules'},
        ),
    ]
